name: CI pipeline 

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop
  
permissions:
  contents: read

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yml

    

  