name: CI pipeline 

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop
  
permissions:
  contents: read

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    name: Validation
    uses: ./.github/workflows/tests.yml

  security:
    name: Run Security Checks
    needs: validation
    uses: ./.github/workflows/security.yml

  build:
    name: Build Docker Images
    needs: security
    uses: ./.github/workflows/Build.yml

  publish:
    name: Publish Docker Images
    needs: build
    uses: ./.github/workflows/publish.yml